=== MalitsPlus/info-pride/utils/wikiPages/cards.schema.json
{
    "$id": "https://_schema.outv.im/info-pride/cards",
    "$schema": "http://json-schema.org/draft-07/schema",
    "description": "Card data for wiki.biligame.com/idolypride",
    "required": [
        "长濑麻奈",
        "川咲樱",
        "一之濑怜",
        "佐伯遥子",
        "白石千纱",
        "兵藤雫",
        "长濑琴乃",
        "伊吹渚",
        "白石沙季",
        "成宫铃",
        "早坂芽衣",
        "天动瑠依",
        "铃村优",
        "奥山堇",
        "神崎莉央",
        "井川葵",
        "小美山爱",
        "赤崎心"
    ],
    "title": "The root schema",
    "type": "object",
    "properties": {
        "长濑麻奈": {
            "$ref": "#/$defs/cardGroup"
        },
        "川咲樱": {
            "$ref": "#/$defs/cardGroup"
        },
        "一之濑怜": {
            "$ref": "#/$defs/cardGroup"
        },
        "佐伯遥子": {
            "$ref": "#/$defs/cardGroup"
        },
        "白石千纱": {
            "$ref": "#/$defs/cardGroup"
        },
        "兵藤雫": {
            "$ref": "#/$defs/cardGroup"
        },
        "长濑琴乃": {
            "$ref": "#/$defs/cardGroup"
        },
        "伊吹渚": {
            "$ref": "#/$defs/cardGroup"
        },
        "白石沙季": {
            "$ref": "#/$defs/cardGroup"
        },
        "成宫铃": {
            "$ref": "#/$defs/cardGroup"
        },
        "早坂芽衣": {
            "$ref": "#/$defs/cardGroup"
        },
        "天动瑠依": {
            "$ref": "#/$defs/cardGroup"
        },
        "铃村优": {
            "$ref": "#/$defs/cardGroup"
        },
        "奥山堇": {
            "$ref": "#/$defs/cardGroup"
        },
        "神崎莉央": {
            "$ref": "#/$defs/cardGroup"
        },
        "井川葵": {
            "$ref": "#/$defs/cardGroup"
        },
        "小美山爱": {
            "$ref": "#/$defs/cardGroup"
        },
        "赤崎心": {
            "$ref": "#/$defs/cardGroup"
        }
    },
    "additionalProperties": false,
    "$defs": {
        "cardGroup": {
            "type": "object",
            "title": "Cards from an idol",
            "additionalProperties": {
                "$ref": "#/$defs/card"
            }
        },
        "card": {
            "type": "object",
            "required": [
                "nameJa",
                "nameCn",
                "type",
                "prop",
                "rarity",
                "vocTop",
                "danTop",
                "visTop",
                "staTop",
                "ski1Typ",
                "ski1NameJa",
                "ski1DescJa",
                "ski1NameCn",
                "ski1DescCn",
                "ski2Typ",
                "ski2NameJa",
                "ski2DescJa",
                "ski2NameCn",
                "ski2DescCn",
                "ski3Typ",
                "ski3NameJa",
                "ski3DescJa",
                "ski3NameCn",
                "ski3DescCn"
            ],
            "properties": {
                "type": {
                    "enum": [
                        "支援",
                        "辅助",
                        "得分"
                    ]
                },
                "rarity": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 5
                },
                "prop": {
                    "enum": [
                        "舞蹈",
                        "歌唱",
                        "表演"
                    ]
                },
                "ski1Typ": {
                    "enum": [
                        "SP",
                        "A"
                    ]
                },
                "ski2Typ": {
                    "enum": [
                        "A",
                        "P"
                    ]
                },
                "ski3Typ": {
                    "enum": [
                        "A",
                        "P"
                    ]
                },
                "vocTop": {
                    "type": "integer"
                },
                "danTop": {
                    "type": "integer"
                },
                "visTop": {
                    "type": "integer"
                },
                "staTop": {
                    "type": "integer"
                }
            },
            "additionalProperties": true
        }
    }
}

=== MalitsPlus/info-pride/utils/wikiPages/cards.json
{"长濑麻奈":{"1":{"nameCn":"你就是我的一切","nameJa":"You're my everything","type":"得分","prop":"歌唱","rarity":5,"vocTop":70806,"danTop":51846,"visTop":45134,"staTop":4895,"ski1Typ":"SP","ski1NameCn":"今后请多多关照","ski1DescCn":"取得1500%得分\n\n暴击率提升状态层数得分提升\n\n体力消耗:563","ski1NameJa":"これからも、よろしくね","ski1DescJa":"1380%のスコア獲得、クリティカル率アップ状態の段階数が多い程効果上昇\nスタミナ:518","ski2Typ":"A","ski2NameCn":"With my heart","ski2DescCn":"取得440%得分\n\n赋予自身5阶段暴击率提升状态 [42拍]\n\n当自身处于气氛高昂状态时\n\n赋予相邻角色5层暴击率提升状态 [30拍]\n\n体力消耗:149  CT:30","ski2NameJa":"With my heart","ski2DescJa":"440%のスコア獲得\n自身に5段階クリティカル率上昇効果[42ビート]\nテンションアップ状態の時 に5段階クリティカル率上昇効果[30ビート]\nスタミナ:149 CT:30","ski3Typ":"P","ski3NameCn":"献给妹妹的歌","ski3DescCn":"赋予自身7层气氛高昂状态 [37拍]\n\n体力消耗:225  CT:50","ski3NameJa":"妹へ届けたい歌","ski3DescJa":"自身に7段階テンションUP効果[32ビート]\nスタミナ:195 CT:50","eruNameCn":"经纪人经验获取提升[宣传]","eruDescCn":"宣传获得的经纪人经验提升6%","eruNameJa":"MEXPアップ【プロモーション】","eruDescJa":"プロモーションの獲得マネージャー経験値6%UP"},"2":{"nameCn":"执子之手","nameJa":"ただ、手を繋ぐだけ","type":"得分","prop":"舞蹈","rarity":5,"vocTop":46645,"danTop":72819,"visTop":53356,"staTop":4405,"ski1Typ":"SP","ski1NameCn":"造就最棒的演出！","ski1DescCn":"获得1570%分数 集目状态层数得分提升 体力消耗:565","ski1NameJa":"最っ高のライブにします！","ski1DescJa":"1570%のスコア獲得、集目状態の段階数が多い程効果上昇 スタミナ:565","ski2Typ":"A","ski2NameCn":"今天是特别的","ski2DescCn":"获得460%分数 赋予蓝属性值最高的2人8层得分提升状态[30拍] 体力消耗:147 CT:30","ski2NameJa":"今日は特別","ski2DescJa":"460%のスコア獲得 ダンスが高い2人に8段階スコア上昇効果[30ビート] スタミナ:147 CT:30","ski3Typ":"P","ski3NameCn":"宝贵的回忆","ski3DescCn":"赋予自身7层集目状态[37拍] 赋予自身9层暴击率提升状态[39拍] 体力消耗:220 CT:50","ski3NameJa":"Precious memories","ski3DescJa":"自身に7段階の集目効果[37ビート] 自身に9段階クリティカル率上昇効果[39ビート] スタミナ:220 CT:50","eruNameCn":"暴击率提升","eruDescCn":"暴击率提升200","eruNameJa":"クリティカルアップ","eruDescJa":"クリティカル200上昇"}},"川咲樱":{"1":{"nameCn":"夜空里绽开的花","nameJa":"夜空に咲く花","type":"辅助","prop":"表演","rarity":2,"vocTop":53524,"danTop":46981,"visTop":67282,"staTop":4895,"ski1Typ":"A","ski1NameCn":"盛开的烟花","ski1DescCn":"取得420%得分\n\n连击数得分提升\n\n赋予自身20层体力消耗提升状态[50拍]\n\n体力消耗:189 CT:50","ski1NameJa":"満開の花火","ski1DescJa":"420%のスコア獲得、コンボ数が多い程効果上昇\n自身に20段階消費スタミナ上昇効果[50ビート]\nスタミナ:189 CT:50","ski2Typ":"A","ski2NameCn":"夏日回忆","ski2DescCn":"取得430%得分\n\n赋予自身9层黄属性提升状态[25拍]\n\n体力消耗:148 CT:30","ski2NameJa":"夏の思い出","ski2DescJa":"430%のスコア獲得\n自身に9段階ビジュアル上昇効果[25ビート]\nスタミナ:148 CT:30","ski3Typ":"P","ski3NameCn":"大家一起穿浴衣","ski3DescCn":"当50连击以上时\n\n赋予黄属性高的3人6层黄属性提升状态[35拍]\n\n体力消耗:215 CT:60","ski3NameJa":"みんなで浴衣","ski3DescJa":"50コンボ以上時\nビジュアルが高い3人に6段階ビジュアル上昇効果[35ビート]\nスタミナ:215 CT:60"},"2":{"nameCn":"元气100倍！","nameJa":"元気100倍！","type":"得分","prop":"歌唱","rarity":3,"vocTop":58473,"danTop":42785,"visTop":37080,"staTop":4576,"ski1Typ":"SP","ski1NameCn":"我也想要闪闪发光！","ski1DescCn":"取得960%得分\n\n连击数得分提升\n\n体力消耗:432","ski1NameJa":"私も輝きたい！","ski1DescJa":"960%のスコア獲得、コンボ数が多い程効果上昇\nスタミナ:432","ski2Typ":"A","ski2NameCn":"青春的汗水","ski2DescCn":"取得450%得分\n\n体力消耗:127 CT:30","ski2NameJa":"青春の汗","ski2DescJa":"450%のスコア獲得\nスタミナ:127 CT:30","ski3Typ":"P","ski3NameCn":"笑容的背后的付出","ski3DescCn":"当自己体力80%以上时\n\n赋予自身7层红属性提升状态[37拍]\n\n体力消耗:213 CT:60","ski3NameJa":"笑顔の裏側","ski3DescJa":"スタミナ80%以上の時\n自身に7段階ボーカル上昇効果[37ビート]\nスタミナ:213 CT:60"},"3":{"nameCn":"多汁的午餐","nameJa":"ジューシーランチ","type":"支援","prop":"舞蹈","rarity":4,"vocTop":52600,"danTop":65353,"visTop":46225,"staTop":4576,"ski1Typ":"A","ski1NameCn":"炸猪排的力量","ski1DescCn":"赋予410%得分\n\n赋予体力最低的1人体力回复4000\n\n体力消耗:151 CT:40","ski1NameJa":"とんかつパワー","ski1DescJa":"410%のスコア獲得\nスタミナが低い1人のスタミナを4000回復\nスタミナ:151 CT:40","ski2Typ":"P","ski2NameCn":"酱料是不是再多一点好？","ski2DescCn":"当50连击以上时\n\n赋予全员9层A技能得分提升状态[46拍]\n\n体力消耗:446  一局仅发动一次","ski2NameJa":"ソースは多め？","ski2DescJa":"50コンボ以上時\n全員に9段階アピールスコア上昇効果[46ビート]\nスタミナ:446","ski3Typ":"P","ski3NameCn":"激动不已","ski3DescCn":"赋予自身12层得分提升状态[34拍]\n\n体力消耗:194 CT:60","ski3NameJa":"胸の高鳴り","ski3DescJa":"自身に12段階スコア上昇効果[34ビート]\nスタミナ:194 CT:60","eruNameCn":"体力回复提升","eruDescCn":"休息的体力回复提升2%","eruNameJa":"元気回復UP","eruDescJa":"リフレッシュの回復量2%上昇"},"4":{"nameCn":"梦的共演","nameJa":"夢の共演","type":"得分","prop":"歌唱","rarity":5,"vocTop":70471,"danTop":52014,"visTop":45302,"staTop":4895,"ski1Typ":"SP","ski1NameCn":"和太阳的光芒一起闪闪发光","ski1DescCn":"取得1550%得分\n\n强化状态种类得分提升\n\n体力消耗:497","ski1NameJa":"太陽の光と共に","ski1DescJa":"1550%のスコア獲得、強化効果が多い程効果上昇\nスタミナ:497","ski2Typ":"A","ski2NameCn":"最喜欢的那个角色","ski2DescCn":"取得430%得分\n\n赋予自身9层红属性提升状态[25拍]\n\n体力消耗:148 CT:30","ski2NameJa":"大好きなあのキャラ","ski2DescJa":"430%のスコア獲得\n自身に9段階ボーカル上昇効果[25ビート]\nスタミナ:148 CT:30","ski3Typ":"P","ski3NameCn":"努力的回报","ski3DescCn":"当100连击以上时\n\n取得120%得分\n\n赋予自身8层红属性提升状态[32拍]\n\n体力消耗:378  一局仅发动一次","ski3NameJa":"人生の倍返し","ski3DescJa":"100コンボ以上時\n120%のスコア獲得\n自身に8段階ボーカル上昇効果[32ビート]\nスタミナ:378","eruNameCn":"歌唱属性提升","eruDescCn":"歌唱属性提升2%","eruNameJa":"ボーカルアップ","eruDescJa":"ボーカル2%上昇"},"5":{"nameCn":"希望成为你的光芒","nameJa":"あなたの光になれるように","type":"辅助","prop":"表演","rarity":5,"vocTop":54195,"danTop":47315,"visTop":66276,"staTop":4895,"ski1Typ":"A","ski1NameCn":"通过我的歌给大家带来活力！","ski1DescCn":"取得530%得分\n\n赋予得分角色2人8层暴击率提升状态[43拍]\n\n体力消耗:174 CT:50","ski1NameJa":"私の歌でみんなに元気を！","ski1DescJa":"530%のスコア獲得\nスコアラータイプ2人に8段階クリティカル率上昇効果[43ビート]\nスタミナ:174 CT:50","ski2Typ":"A","ski2NameCn":"克服重重压力","ski2DescCn":"取得480%得分\n\n赋予得分角色2人6层黄属性提升状态[53拍]\n\n体力消耗:176 CT:50","ski2NameJa":"重圧を乗り越えて","ski2DescJa":"480%のスコア獲得\nスコアラータイプ2人に6段階ビジュアル上昇効果[53ビート]\nスタミナ:176 CT:50","ski3Typ":"P","ski3NameCn":"心中充满勇气","ski3DescCn":"谁的SP技能发动前\n\n赋予对象7层SP技能得分提升状态\n\n体力消耗:306 CT:70","ski3NameJa":"胸いっぱいの勇気","ski3DescJa":"誰かがSPスキル発動前\n対象1人に7段階SPスキルスコア上昇効果[5ビート]\nスタミナ:306 CT:70","eruNameCn":"暴击得分提升","eruDescCn":"暴击得分上升2%","eruNameJa":"クリティカルスコアアップ","eruDescJa":"クリティカルスコア2%上昇"},"6":{"nameCn":"笑口开，福运来！","nameJa":"笑う門には福来るだよ！","type":"支援","prop":"歌唱","rarity":5,"vocTop":69631,"danTop":55202,"visTop":47987,"staTop":4405,"ski1Typ":"A","ski1NameCn":"橙色的早霜","ski1DescCn":"取得500%得分\n\n全员回复25%的最大体力值\n\n对决演出模式下\n赋予对手中心角色8层红属性降低状态[50拍]\n\n体力消耗:205 CT:40","ski1NameJa":"朝焼けのオレンジ","ski1DescJa":"500%のスコア獲得\n全員に対象最大スタミナの25%のスタミナ回復効果\n[ライブバトルのみ]相手のセンターに8段階ボーカル低下効果[50ビート]\nスタミナ:205 CT:40","ski2Typ":"P","ski2NameCn":"留下爪印","ski2DescCn":"当50连击以上时\n\n全员减少30CT\n\n赋予中心角色5层暴击系数提升状态[75拍]\n\n体力消耗:468 一局仅发动一次","ski2NameJa":"爪痕を残してなんぼ","ski2DescJa":"50コンボ以上時\n全員のCTを30減少\nセンターに5段階クリティカル係数上昇効果[75ビート]\nスタミナ:469","ski3Typ":"P","ski3NameCn":"新年祝福","ski3DescCn":"赋予红属性最高2人\n8层得分提升状态[43拍]\n\n赋予红属性最高的两人12层体力消耗降低状态[38拍]\n\n体力消耗:221 CT:50","ski3NameJa":"お正月リフレッシュ","ski3DescJa":"ボーカルが高い2人に8段階スコア上昇効果[43ビート]\nボーカルが高い2人に12段階消費スタミナ低下効果[38ビート]\nスタミナ:221 CT:50","eruNameCn":"经纪人经验获取提升【粉丝活动】","eruDescCn":"粉丝活动取得的经纪人经验提升15%","eruNameJa":"MEXPアップ【ファンイベント】","eruDescJa":"ファンイベントの獲得マネージャー経験値15%UP"}},"一之濑怜":{"1":{"nameCn":"夜间的自主训练","nameJa":"夜の自主トレ","type":"支援","prop":"舞蹈","rarity":3,"vocTop":41358,"danTop":58473,"visTop":47063,"staTop":3743,"ski1Typ":"A","ski1NameCn":"時に孤独に","ski1DescCn":"取得330%得分\n\n蓝属性高的3人CT减少20\n\n体力消耗:121 CT:30","ski1NameJa":"時に孤独に","ski1DescJa":"330%のスコア獲得\nダンスが高い3人のCTを20減少\nスタミナ:121 CT:30","ski2Typ":"A","ski2NameCn":"仲間と一緒に","ski2DescCn":"取得380%得分\n\n体力最低的1人体力回复3300\n\n体力消耗:136 CT:40","ski2NameJa":"仲間と一緒に","ski2DescJa":"380%のスコア獲得\nスタミナが低い1人のスタミナを3300回復\nスタミナ:136 CT:40","ski3Typ":"P","ski3NameCn":"万事徹底","ski3DescCn":"每节拍\n\n10%概率取得110%得分\n\n体力消耗:154 CT:40","ski3NameJa":"万事徹底","ski3DescJa":"ビート時\n110%のスコア獲得\nスタミナ:154 CT:40"},"2":{"nameCn":"秘密的兴趣","nameJa":"密かなお楽しみ","type":"得分","prop":"舞蹈","rarity":4,"vocTop":41442,"danTop":65353,"visTop":47819,"staTop":5115,"ski1Typ":"SP","ski1NameCn":"必ずトップになろう！","ski1DescCn":"取得1080%得分\n\n强化状态种类得分提升\n\n当自己处于蓝属性提升状态时 额外取得510%得分\n\n体力消耗:475","ski1NameJa":"必ずトップになろう！","ski1DescJa":"1080%のスコア獲得、強化効果が多い程効果上昇\nダンスアップ状態の時 510%のスコア獲得\nスタミナ:475","ski2Typ":"A","ski2NameCn":"家族の力","ski2DescCn":"取得500%得分\n\n体力消耗:141 CT:30","ski2NameJa":"家族の力","ski2DescJa":"500%のスコア獲得\nスタミナ:141 CT:30","ski3Typ":"P","ski3NameCn":"負けない気持ち","ski3DescCn":"当自己处于蓝属性提升状态时\n\n赋予自身7层蓝属性提升状态[44拍]\n\n赋予自身10层体力消耗提升状态[65拍]\n\n体力消耗:252 CT:65","ski3NameJa":"負けない気持ち","ski3DescJa":"ダンスアップ状態の時\n自身に7段階ダンス上昇効果[44ビート]\n自身に10段階消費スタミナ上昇効果[65ビート]\nスタミナ:252 CT:65","eruNameCn":"舞蹈属性提升","eruDescCn":"舞蹈属性提升2%","eruNameJa":"ダンスアップ","eruDescJa":"ダンス2%上昇"},"3":{"nameCn":"高台上微风轻拂","nameJa":"高台をかける薫風","type":"辅助","prop":"舞蹈","rarity":5,"vocTop":46981,"danTop":67116,"visTop":53692,"staTop":4895,"ski1Typ":"A","ski1NameCn":"優勝への決意","ski1DescCn":"取得430%得分\n\n赋予全员6层蓝属性提升状态[25拍]\n\n体力消耗:147 CT:30","ski1NameJa":"優勝への決意","ski1DescJa":"430%のスコア獲得\n全員に6段階ダンス上昇効果[25ビート]\nスタミナ:147 CT:30","ski2Typ":"P","ski2NameCn":"踊る理由","ski2DescCn":"取得150%得分\n\n赋予自身2层暴击率提升状态[42拍]\n\n体力消耗:251 CT:50","ski2NameJa":"踊る理由","ski2DescJa":"150%のスコア獲得\n自身に2段階クリティカル率上昇効果[42ビート]\nスタミナ:251 CT:50","ski3Typ":"P","ski3NameCn":"精一杯の恩返し","ski3DescCn":"当自己暴击时\n\n取得85%得分\n\n自身的CT减少15\n\n体力消耗:234 CT:60","ski3NameJa":"精一杯の恩返し","ski3DescJa":"クリティカル発動時\n85%のスコア獲得\n自身のCTを15減少\nスタミナ:234 CT:60","eruNameCn":"舞蹈属性提升","eruDescCn":"舞蹈属性提升2%","eruNameJa":"ダンスアップ","eruDescJa":"ダンス2%上昇"},"4":{"nameCn":"百折不挠","nameJa":"失敗なんて恐れない","type":"得分","prop":"表演","rarity":5,"vocTop":53859,"danTop":47315,"visTop":71645,"staTop":4405,"ski1Typ":"SP","ski1NameCn":"ウソみたいに、体が軽い","ski1DescCn":"取得1000%得分\n\n强化状态种类得分提升\n\n当自己处于黄属性提升状态时\n\n取得780%得分\n\n体力消耗:715","ski1NameJa":"ウソみたいに、体が軽い","ski1DescJa":"1000%のスコア獲得、強化効果が多い程効果上昇\nビジュアルアップ状態の時 780%のスコア獲得\nスタミナ:715","ski2Typ":"A","ski2NameCn":"負けず嫌いのダンス","ski2DescCn":"取得450%得分\n\n赋予自身9层黄属性提升状态[45拍]\n\n体力消耗:176 CT:50","ski2NameJa":"負けず嫌いのダンス","ski2DescJa":"450%のスコア獲得\n自身に9段階ビジュアル上昇効果[45ビート]\nスタミナ:176 CT:50","ski3Typ":"A","ski3NameCn":"スランプ脱却","ski3DescCn":"取得490%得分\n\n自身的体力回复400\n\n体力消耗:154 CT:50","ski3NameJa":"スランプ脱却","ski3DescJa":"490%のスコア獲得\n自身のスタミナを400回復\nスタミナ:154 CT:50","eruNameCn":"表演属性提升","eruDescCn":"表演属性提升2%","eruNameJa":"ビジュアルアップ","eruDescJa":"ビジュアル2%上昇"},"5":{"nameCn":"灵魂之舞","nameJa":"ココロ Distance","type":"辅助","prop":"舞蹈","rarity":2,"vocTop":47651,"danTop":66444,"visTop":53692,"staTop":4895,"ski1Typ":"A","ski1NameCn":"私の選んだ仕事","ski1DescCn":"取得380%得分\n\n得分角色2人的强化状态延长6\n\n体力消耗：125 CT：50","ski1NameJa":"私の選んだ仕事","ski1DescJa":"380%のスコア獲得\nスコアラータイプ2人の強化効果を6延長\nスタミナ：125 CT：50","ski2Typ":"A","ski2NameCn":"力を貸して","ski2DescCn":"取得580%得分\n\n体力消耗：163 CT：50","ski2NameJa":"力を貸して","ski2Desc
