=== MalitsPlus/info-pride/utils/wikiPages/idols.schema.json
{
    "$id": "https://_schema.outv.im/info-pride/idols",
    "$schema": "http://json-schema.org/draft-07/schema",
    "description": "Idol data for wiki.biligame.com/idolypride",
    "required": [
        "长濑麻奈",
        "川咲樱",
        "一之濑怜",
        "佐伯遥子",
        "白石千纱",
        "兵藤雫",
        "长濑琴乃",
        "伊吹渚",
        "白石沙季",
        "成宫铃",
        "早坂芽衣",
        "天动瑠依",
        "铃村优",
        "奥山堇",
        "神崎莉央",
        "井川葵",
        "小美山爱",
        "赤崎心"
    ],
    "title": "The root schema",
    "type": "object",
    "properties": {
        "长濑麻奈": {
            "$ref": "#/$defs/idolInfo"
        },
        "川咲樱": {
            "$ref": "#/$defs/idolInfo"
        },
        "一之濑怜": {
            "$ref": "#/$defs/idolInfo"
        },
        "佐伯遥子": {
            "$ref": "#/$defs/idolInfo"
        },
        "白石千纱": {
            "$ref": "#/$defs/idolInfo"
        },
        "兵藤雫": {
            "$ref": "#/$defs/idolInfo"
        },
        "长濑琴乃": {
            "$ref": "#/$defs/idolInfo"
        },
        "伊吹渚": {
            "$ref": "#/$defs/idolInfo"
        },
        "白石沙季": {
            "$ref": "#/$defs/idolInfo"
        },
        "成宫铃": {
            "$ref": "#/$defs/idolInfo"
        },
        "早坂芽衣": {
            "$ref": "#/$defs/idolInfo"
        },
        "天动瑠依": {
            "$ref": "#/$defs/idolInfo"
        },
        "铃村优": {
            "$ref": "#/$defs/idolInfo"
        },
        "奥山堇": {
            "$ref": "#/$defs/idolInfo"
        },
        "神崎莉央": {
            "$ref": "#/$defs/idolInfo"
        },
        "井川葵": {
            "$ref": "#/$defs/idolInfo"
        },
        "小美山爱": {
            "$ref": "#/$defs/idolInfo"
        },
        "赤崎心": {
            "$ref": "#/$defs/idolInfo"
        }
    },
    "additionalProperties": false,
    "$defs": {
        "idolInfo": {
            "type": "object",
            "title": "Idol info",
            "description": "Information for an idol",
            "examples": [
                {
                    "nameJa": "長瀬琴乃",
                    "nameCn": "长濑琴乃",
                    "birthday": "12月25日",
                    "team": "月のテンペスト",
                    "cv": "橘美来",
                    "desc": "继承姐姐长濑麻奈的遗志，立志成为偶像的少女. \n在组合成立之初，也有刻意避开与人交流而喜欢独处的时候. 但最终在和成员一同跨越苦难的过程中，同大家一起成长，\n并且成为了能够引领大家的存在."
                }
            ],
            "properties": {
                "nameJa": {
                    "type": "string",
                    "title": "Name in Japanese",
                    "examples": [
                        "長瀬琴乃"
                    ]
                },
                "nameCn": {
                    "type": "string",
                    "title": "Name in Chinese",
                    "examples": [
                        "长濑琴乃"
                    ]
                },
                "birthday": {
                    "type": "string",
                    "examples": [
                        "12月25日"
                    ]
                },
                "team": {
                    "enum": [
                        "月のテンペスト",
                        "サニーピース",
                        "星见事务所",
                        "TRINITYAiLE",
                        "LizNoir"
                    ]
                },
                "cv": {
                    "type": "string",
                    "examples": [
                        "橘美来"
                    ]
                },
                "desc": {
                    "type": "string",
                    "title": "Description"
                }
            }
        }
    }
}

=== MalitsPlus/info-pride/utils/wikiPages/cardSkills.json
{"长濑麻奈":{"1":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":1500},{"type":"staminaCost","staminaCost":563}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":440},{"type":"statisGive","statusGive":{"on":"自身","status":"暴击率提升"}},{"type":"limitLength","limitLength":42},{"type":"when","when":{"on":"自身","status":"气氛高昂"}},{"type":"statusUp","statusUp":{"on":"相邻角色","status":"暴击率提升","level":5}},{"type":"limitLength","limitLength":30},{"type":"staminaCost","staminaCost":149},{"type":"colddownTime","colddownTime":30}],"ski3":[{"type":"statusUp","statusUp":{"on":"自身","status":"气氛高昂","level":7}},{"type":"limitLength","limitLength":37},{"type":"staminaCost","staminaCost":225},{"type":"colddownTime","colddownTime":50}]},"2":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":1570},{"type":"staminaCost","staminaCost":565}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":460},{"type":"limitLength","limitLength":30},{"type":"staminaCost","staminaCost":147},{"type":"colddownTime","colddownTime":30}],"ski3":[{"type":"statusUp","statusUp":{"on":"自身","status":"集目","level":7}},{"type":"limitLength","limitLength":37},{"type":"statusUp","statusUp":{"on":"自身","status":"暴击率提升","level":9}},{"type":"limitLength","limitLength":39},{"type":"staminaCost","staminaCost":220},{"type":"colddownTime","colddownTime":50}]}},"川咲樱":{"1":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":420},{"type":"comboScoreUp"},{"type":"statusUp","statusUp":{"on":"自身","status":"体力消耗提升","level":20}},{"type":"limitLength","limitLength":50},{"type":"staminaCost","staminaCost":189},{"type":"colddownTime","colddownTime":50}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":430},{"type":"statusUp","statusUp":{"on":"自身","status":"黄属性提升","level":9}},{"type":"limitLength","limitLength":25},{"type":"staminaCost","staminaCost":148},{"type":"colddownTime","colddownTime":30}],"ski3":[{"type":"when","when":{"combo":{"$gt":50}}},{"type":"statusUp","statusUp":{"on":"黄","status":"黄属性提升","level":6}},{"type":"limitLength","limitLength":35},{"type":"staminaCost","staminaCost":215},{"type":"colddownTime","colddownTime":60}]},"2":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":960},{"type":"comboScoreUp"},{"type":"staminaCost","staminaCost":432}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":450},{"type":"staminaCost","staminaCost":127},{"type":"colddownTime","colddownTime":30}],"ski3":[{"type":"when","when":{"on":"自己","prop":"体力","value":{"$gt":80}}},{"type":"statusUp","statusUp":{"on":"自身","level":7,"color":"红"}},{"type":"limitLength","limitLength":37},{"type":"staminaCost","staminaCost":213},{"type":"colddownTime","colddownTime":60}]},"3":{"ski1":[{"type":"staminaCost","staminaCost":151},{"type":"colddownTime","colddownTime":40}],"ski2":[{"type":"when","when":{"combo":{"$gt":50}}},{"type":"statusUp","statusUp":{"on":"全员","status":"得分提升","level":9}},{"type":"limitLength","limitLength":46},{"type":"staminaCost","staminaCost":446},{"type":"limit","limit":"once"}],"ski3":[{"type":"statusUp","statusUp":{"on":"自身","status":"得分提升","level":12}},{"type":"limitLength","limitLength":34},{"type":"staminaCost","staminaCost":194},{"type":"colddownTime","colddownTime":60}]},"4":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":1700},{"type":"staminaCost","staminaCost":545}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":430},{"type":"statusUp","statusUp":{"on":"自身","level":9,"color":"红"}},{"type":"limitLength","limitLength":25},{"type":"staminaCost","staminaCost":148},{"type":"colddownTime","colddownTime":30}],"ski3":[{"type":"when","when":{"combo":{"$gt":100}}},{"type":"scoreMultiplier","scoreMultiplyPerc":140},{"type":"statusUp","statusUp":{"on":"自身","level":9,"color":"红"}},{"type":"limitLength","limitLength":32},{"type":"staminaCost","staminaCost":432},{"type":"limit","limit":"once"}]},"5":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":560},{"type":"statusUp","statusUp":{"on":"2","status":"暴击率提升","level":8}},{"type":"limitLength","limitLength":48},{"type":"staminaCost","staminaCost":186},{"type":"colddownTime","colddownTime":50}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":480},{"type":"statusUp","statusUp":{"on":"2","status":"黄属性提升","level":6}},{"type":"limitLength","limitLength":53},{"type":"staminaCost","staminaCost":176},{"type":"colddownTime","colddownTime":50}],"ski3":[{"type":"when","when":{"before":"SP"}},{"type":"staminaCost","staminaCost":306},{"type":"colddownTime","colddownTime":50}]},"6":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":500},{"type":"limitLength","limitLength":50},{"type":"staminaCost","staminaCost":205},{"type":"colddownTime","colddownTime":40}],"ski2":[{"type":"when","when":{"combo":{"$gt":50}}},{"type":"statusUp","statusUp":{"on":"中心角色","status":"暴击系数提升","level":5}},{"type":"limitLength","limitLength":75},{"type":"staminaCost","staminaCost":468},{"type":"limit","limit":"once"}],"ski3":[{"type":"limitLength","limitLength":43},{"type":"limitLength","limitLength":38},{"type":"staminaCost","staminaCost":221},{"type":"colddownTime","colddownTime":50}]}},"一之濑怜":{"1":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":330},{"type":"ctDecrease","ctDecrease":{"number":20,"on":"蓝"}},{"type":"staminaCost","staminaCost":121},{"type":"colddownTime","colddownTime":30}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":380},{"type":"staminaCost","staminaCost":136},{"type":"colddownTime","colddownTime":40}],"ski3":[{"type":"when","when":{"every":"beat"}},{"type":"scoreMultiplier","scoreMultiplyPerc":110,"probabilityPerc":10},{"type":"staminaCost","staminaCost":154},{"type":"colddownTime","colddownTime":40}]},"2":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":1080},{"type":"when","when":{"on":"自己","status":"蓝属性提升"}},{"type":"scoreMultiplier","scoreMultiplyPerc":510},{"type":"staminaCost","staminaCost":475}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":500},{"type":"staminaCost","staminaCost":141},{"type":"colddownTime","colddownTime":30}],"ski3":[{"type":"when","when":{"on":"自己","status":"蓝属性提升"}},{"type":"statusUp","statusUp":{"on":"自身","level":7,"color":"蓝"}},{"type":"limitLength","limitLength":44},{"type":"statusUp","statusUp":{"on":"自身","status":"体力消耗提升","level":10}},{"type":"limitLength","limitLength":65},{"type":"staminaCost","staminaCost":252},{"type":"colddownTime","colddownTime":65}]},"3":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":430},{"type":"statusUp","statusUp":{"on":"全员","level":6,"color":"蓝"}},{"type":"limitLength","limitLength":25},{"type":"staminaCost","staminaCost":147},{"type":"colddownTime","colddownTime":30}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":150},{"type":"statusUp","statusUp":{"on":"自身","status":"暴击率提升","level":2}},{"type":"limitLength","limitLength":42},{"type":"staminaCost","staminaCost":251},{"type":"colddownTime","colddownTime":50}],"ski3":[{"type":"when","when":{"critical":{"$eq":true},"on":"self"}},{"type":"scoreMultiplier","scoreMultiplyPerc":85},{"type":"ctDecrease","ctDecrease":{"number":15,"on":"自身"}},{"type":"staminaCost","staminaCost":234},{"type":"colddownTime","colddownTime":60}]},"4":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":1000},{"type":"when","when":{"on":"自己","status":"黄属性提升"}},{"type":"scoreMultiplier","scoreMultiplyPerc":780},{"type":"staminaCost","staminaCost":715}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":450},{"type":"statusUp","statusUp":{"on":"自身","status":"黄属性提升","level":9}},{"type":"limitLength","limitLength":45},{"type":"staminaCost","staminaCost":176},{"type":"colddownTime","colddownTime":50}],"ski3":[{"type":"scoreMultiplier","scoreMultiplyPerc":490},{"type":"staminaUp","staminaUp":{"number":400,"on":"自身"}},{"type":"staminaCost","staminaCost":154},{"type":"colddownTime","colddownTime":50}]},"5":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":380},{"type":"staminaCost","staminaCost":125},{"type":"colddownTime","colddownTime":50}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":580},{"type":"staminaCost","staminaCost":163},{"type":"colddownTime","colddownTime":50}],"ski3":[{"type":"scoreMultiplier","scoreMultiplyPerc":90},{"type":"statusUp","statusUp":{"on":"中心角色","level":5,"color":"蓝"}},{"type":"limitLength","limitLength":55},{"type":"staminaCost","staminaCost":352},{"type":"limit","limit":"once"}]},"6":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":500},{"type":"statisGive","statusGive":{"on":"黄","status":"黄属性提升"}},{"type":"limitLength","limitLength":50},{"type":"staminaCost","staminaCost":186},{"type":"colddownTime","colddownTime":50}],"ski2":[{"type":"scoreMultiplier","scoreMultiplyPerc":390},{"type":"staminaCost","staminaCost":176},{"type":"colddownTime","colddownTime":50}],"ski3":[{"type":"statusUp","statusUp":{"on":"自身","status":"得分提升","level":5}},{"type":"limitLength","limitLength":53},{"type":"staminaCost","staminaCost":200},{"type":"colddownTime","colddownTime":40}]}},"佐伯遥子":{"1":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":370},{"type":"statusUp","statusUp":{"on":"蓝","level":7,"color":"蓝"}},{"type":"limitLength","limitLength":25},{"type":"staminaCost","staminaCost":125},{"type":"colddownTime","colddownTime":30}],"ski2":[{"type":"statusUp","statusUp":{"on":"蓝","status":"得分提升","level":6}},{"type":"limitLength","limitLength":38},{"type":"statusUp","statusUp":{"on":"蓝","status":"体力消耗降低","level":10}},{"type":"limitLength","limitLength":38},{"type":"staminaCost","staminaCost":211},{"type":"colddownTime","colddownTime":50}],"ski3":[{"type":"when","when":{"every":"beat"}},{"type":"scoreMultiplier","scoreMultiplyPerc":110,"probabilityPerc":10},{"type":"staminaCost","staminaCost":154},{"type":"colddownTime","colddownTime":40}]},"2":{"ski1":[{"type":"scoreMultiplier","scoreMultiplyPerc":440},{"type":"statusUp","statusUp":{"on":"1","status":"得分提升","level":9}},{"type":"limitLength","limitLength":40},{"type":"statusUp","statusUp":{"on":"自身","status":"体力消耗提升","level":20}},{"type":"limitLength","limitLength":20},{"type":"staminaCost","stamin
